baseURL = 'https://quinguyen2004.github.io/NguyenDucQui_Blog/'
languageCode = 'vi'
title = 'Blog Lập Trình'
theme = "PaperMod"
publishDir = "docs"

[params]
    defaultTheme = "light"
    ShowShareButtons = true
    ShowCodeCopyButtons = true
    [params.assets]
        disableFingerprinting = true
    # -------------------------------------------------------
    [params.profileMode]
        enabled = true
        title = "NGUYỄN ĐỨC QUI"
        subtitle = "Bạn sẽ bắt đầu hiểu tại sao bài tập này được gọi là Mô hình Dickens, liên quan đến việc xây dựng tư duy lập trình mạng vững chắc."
        
        # QUAN TRỌNG: Đã sửa lại đúng tên file ảnh trong máy bạn
        imageUrl = "anhtrangchu.jpg"
        
        imageTitle = "Avatar"
        imageWidth = 400 
        imageHeight = 400
        
        [[params.profileMode.buttons]]
            name = "KHÁM PHÁ NGAY"
            url = "/posts"

    # 4. Icon mạng xã hội bên dưới
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/QuiNguyen2004"
    [[params.socialIcons]]
        name = "facebook"
        url = "https://facebook.com/link-cua-ban"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Trang Chủ"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "blog"
    name = "Bài Viết"
    url = "/posts"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "Profile"
    url = "/about"
    weight = 30