baseURL = 'https://quinguyen2004.github.io/NguyenDucQui_Blog/'
languageCode = 'vi'
title = 'Blog Lập Trình'
theme = "PaperMod"
publishDir = "docs"

[params]
    defaultTheme = "auto"
    ShowShareButtons = true
    ShowCodeCopyButtons = true

    # --- KHẮC PHỤC LỖI GIAO DIỆN KHÔNG HIỆN (QUAN TRỌNG) ---
    [params.assets]
        disableFingerprinting = true
    # -------------------------------------------------------

    # Phần Profile ở trang chủ
    [params.profileMode]
        enabled = true
        title = "Nguyen Duc Qui"
        subtitle = "Network & Web Developer"
        imageUrl = "https://github.com/QuiNguyen2004.png"
        imageTitle = "Avatar"
        imageWidth = 120
        imageHeight = 120

    # Các icon mạng xã hội
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/QuiNguyen2004"
    [[params.socialIcons]]
        name = "facebook"
        url = "https://facebook.com/link-cua-ban"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Trang Chủ"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "blog"
    name = "Bài Viết"
    url = "/posts"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "Profile"
    url = "/about"
    weight = 30