baseURL = 'https://quinguyen2004.github.io/NguyenDucQui_Blog/'
publishDir = 'docs'
languageCode = 'vi'
title = 'DUC QUI'
theme = "PaperMod"

[params]
    defaultTheme = "light"
    ShowCodeCopyButtons = true
    
    [params.assets]
        disableFingerprinting = true

    # --- CẤU HÌNH PROFILE (AVATAR) ---
    [params.profileMode]
        enabled = true
        title = "NGUYỄN ĐỨC QUI"
        subtitle = "Với tư duy cầu tiến và khả năng thích nghi nhanh, tôi sẵn sàng cống hiến hết mình để tạo ra giá trị ngay lập tức."
        
        # Đảm bảo ảnh avarta1.jpg nằm trong thư mục static/avarta1.jpg
        imageUrl = "avarta1.jpg"
        imageTitle = "Avatar"
        imageWidth = 200
        imageHeight = 200
        
        [[params.profileMode.buttons]]
            name = "KHÁM PHÁ NGAY"
            url = "posts/"  # Sửa lại thành posts/ để bấm vào xem bài học

    # --- MẠNG XÃ HỘI ---
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/QuiNguyen2004"
    [[params.socialIcons]]
        name = "facebook"
        url = "https://www.facebook.com/qui.nguyen.660694"

# --- MENU ---
[menu]
  [[menu.main]]
    identifier = "home"
    name = "HOME"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "courses"
    name = "COURSE"
    url = "posts/"
    weight = 20

  [[menu.main]]
    identifier = "summary"
    name = "SUMMARY"
    url = "summary/"
    weight = 30  

  [[menu.main]]
    identifier = "about"
    name = "ABOUT"
    url = "about/"
    weight = 40

  [[menu.main]]
    identifier = "contact"
    name = "CONTACT"
    url = "contact/"
    weight = 50

# --- CHO PHÉP CHẠY HTML TRONG MARKDOWN ---
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true