baseURL = 'https://quinguyen2004.github.io/NguyenDucQui_Blog/'
publishDir = 'docs'
languageCode = 'vi'
title = 'Blog Lập Trình'
theme = "PaperMod"

[params]
    defaultTheme = "light"
    ShowShareButtons = true
    ShowCodeCopyButtons = true
    [params.assets]
        disableFingerprinting = true
    # -------------------------------------------------------
    [params.profileMode]
        enabled = true
        title = "NGUYỄN ĐỨC QUI"
        subtitle = "Bạn sẽ bắt đầu hiểu tại sao bài tập này được gọi là Mô hình Dickens, liên quan đến việc xây dựng tư duy lập trình mạng vững chắc."
        
        # QUAN TRỌNG: Đã sửa lại đúng tên file ảnh trong máy bạn
        imageUrl = "anhtrangchu.jpg"
        
        imageTitle = "Avatar"
        imageWidth = 400 
        imageHeight = 400
        
        [[params.profileMode.buttons]]
            name = "KHÁM PHÁ NGAY"
            url = "http://localhost:1313/NguyenDucQui_Blog/about/"

    # 4. Icon mạng xã hội bên dưới
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/QuiNguyen2004"
    [[params.socialIcons]]
        name = "facebook"
        url = "https://facebook.com/link-cua-ban"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "HOME"
    url = "/"
    weight = 10

  # MENU CHA
  [[menu.main]]
    identifier = "courses"
    name = "KHÓA HỌC"
    url = "/posts"
    weight = 20

  [[menu.main]]
    identifier = "gellery"
    name = "GELLERY"
    url = "/gellery"
    weight = 30  

  [[menu.main]]
    identifier = "about"
    name = "ABOUT"
    url = "/about"
    weight = 40

  [[menu.main]]
    identifier = "contact"
    name = "CONTACT"
    url = "/contact"
    weight = 50

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true