baseURL = 'https://quinguyen2004.github.io/NguyenDucQui_Blog/'
publishDir = "docs"
languageCode = "vi"
title = "Blog Lập Trình"
theme = "PaperMod"

[params]
    defaultTheme = "auto"
    ShowShareButtons = true
    ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Trang Chủ"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "blog"
    name = "Bài Viết"
    url = "/posts"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "Profile"
    url = "/about"
    weight = 30